import React from 'react'
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Provider from '../utils/providers/SessionProvider';
import { AlertProvider } from '../utils/providers/AlertProvider';

const lato = Lato({
  weight: ["100", "300","400", "700", "700"],       // Puedes elegir "100", "300", "400", "700", "900" o un arreglo de estos valores
  subsets: ["latin"]
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={lato.className}
      >
        {children}
      </body>
    </html>
  );
}
